const GAME_SIZE_WIDTH = 560;
const GAME_SIZE_HEIGHT = 560;

const FPS = 30;

const TITLE_WIDTH = 400;
const TITLE_HEIGHT = 150;
const TITLE_X = GAME_SIZE_WIDTH / 2 - TITLE_WIDTH / 2;
const TITLE_Y = 200;

const HEAD_WIDTH = 800;
const HEAD_HEIGHT = 500;
const HEAD_X = GAME_SIZE_WIDTH / 2 - HEAD_WIDTH / 2;
const HEAD_Y = GAME_SIZE_HEIGHT - HEAD_HEIGHT;

const GROW_AREA_WIDTH = 500;
const GROW_AREA_HEIGHT = 230;

const GROW_AREA_X = HEAD_X + HEAD_WIDTH / 2 - GROW_AREA_WIDTH / 2;
const GROW_AREA_Y = HEAD_Y + 150;

const HAIR_WIDTH = 20;
const HAIR_HEIGHT = 40;

const GAME_TIME = 10;
const TIME_BAR_HEIGHT = 15;

const RESULT_TITLE_LABEL_WIDTH = 300;
const RESULT_TITLE_LABEL_X = GAME_SIZE_WIDTH / 2 - RESULT_TITLE_LABEL_WIDTH / 2;
const RESULT_TITLE_LABEL_Y = 30;
const RESULT_SCORE_LABEL_WIDTH = GAME_SIZE_WIDTH;
const RESULT_SCORE_LABEL_X = 0;
const RESULT_SCORE_LABEL_Y = 200;

const AGAIN_BUTTON_WIDTH = 200;
const AGAIN_BUTTON_HEIGHT = 30;
const AGAIN_BUTTON_X = GAME_SIZE_WIDTH / 2 - AGAIN_BUTTON_WIDTH / 2;
const AGAIN_BUTTON_Y = 400;