const GAME_SIZE_WIDTH = 960;
const GAME_SIZE_HEIGHT = 960;

const FPS = 30;

const SCENE = 4;

const TOP = 0;
const DESCRIPTION = 1;
const GAME = 2;
const RESULT = 3;

const TITLE_WIDTH = 600;
const TITLE_HEIGHT = 300;
const TITLE_X = GAME_SIZE_WIDTH / 2 - TITLE_WIDTH / 2;
const TITLE_Y = 200;

const HEAD_WIDTH = 800;
const HEAD_HEIGHT = 500;
const HEAD_X = GAME_SIZE_WIDTH / 2 - HEAD_WIDTH / 2;
const HEAD_Y = GAME_SIZE_HEIGHT - HEAD_HEIGHT;

const GROW_AREA_WIDTH = 400;
const GROW_AREA_HEIGHT = 100;

const GROW_AREA_X = HEAD_X + HEAD_WIDTH / 2 - GROW_AREA_WIDTH / 2;
const GROW_AREA_Y = HEAD_Y + HEAD_HEIGHT / 2;

const HAIR_WIDTH = 20;
const HAIR_HEIGHT = 40;